# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='line',
        ),
        migrations.AddField(
            model_name='line',
            name='quotation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Quotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='first_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
