# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_auto_20181005_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='creation',
            new_name='create_date',
        ),
    ]
