# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_auto_20181005_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='first_name', unique_with=['first_name', 'last_name', 'id']),
        ),
    ]
