# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0007_auto_20181005_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='statut',
            field=models.CharField(choices=[('PROGRESS', 'In progress'), ('RECALL', 'In recall'), ('DONE', 'Done')], default='PROGRESS', max_length=20),
        ),
    ]
