# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0009_auto_20181009_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
